name: goblinfight
version:             0.1.0.0
github: "Geometer1729/GoblinFight"
license: GPL-2

description: Please see the README on GitHub at <https://github.com/Geometer1729/GoblinFight#readme>

extra-source-files:
- README.md

dependencies:
- base
- containers
- deepseq
- directory
- flow
- free
- gloss
- gloss-juicy
- lens
- list-t
- mtl
- process
- random
- template-haskell

library:
  source-dirs:
  - src
  - ais
  ghc-options:
  - -O2
  - -Wall
  - -Wno-orphans

executables:
  client-exe:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
      #- -threaded
      #- -rtsopts
      #- -with-rtsopts=-N
    - -O2
    - -Wall
    - -Wno-orphans
    dependencies:
    - goblinfight
